[project]
name = "glimpse-attention-networks"
version = "0.1.0"
description = ""
authors = [
    {name = "Victor Ng"}
]
readme = "README.md"
requires-python = "~3.12"
dependencies = [
    "opencv-python-headless (>=4.11.0.86,<5.0.0.0)",
    "torch",
    "torchvision",
    "lightning (==2.5.1)",
    "matplotlib (>=3.10.3,<4.0.0)",
    "scipy (>=1.15.3,<2.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
torch = { url = "https://download.pytorch.org/whl/cu124/torch-2.5.1%2Bcu124-cp312-cp312-linux_x86_64.whl"}
torchvision = { url = "https://download.pytorch.org/whl/cu124/torchvision-0.20.1%2Bcu124-cp312-cp312-linux_x86_64.whl"}

